name: first workflow

on:
  workflow_dispatch:
  
jobs:
  firstJob:
    runs-on: self-hosted
    steps:
      - name: first job script
        shell: bash
        run:
          echo Hello World!
        
  secondJob: 
    runs-on: self-hosted
    steps:
      - name: Second job script
        shell: bash
        run:
          echo Hello World!
          echo This is muilti line script.   
      
