name: first workflow

on:
  workflow_dispatch:
  
jobs:
  firstJob:
    runs-on: self-hosted
    steps:
      - name: first job script
        shell: cmd
        run: echo Hello World! This is the first job.
        
  secondJob: 
    runs-on: self-hosted
    steps:
      - name: Second job script
        shell: bash
        run: echo Hello World!
             echo This is muilti line script.   
      
